config/routes.rb
OtterEvents::Application.routes.draw do
  devise_for :user_tbls

  resources :microposts
  resources :dashboard
  resources :users
  resources :event
  
  root :to => "home#index"
  
  match "/events" => redirect("/event")

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user_tbl
  attr_accessible :description, :name, :timeStart, :timeEnd, :location, :private, :user_id
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
    validates :content, :length => { :maximum => 140 }
end

app/models/user_tbl.rb
class UserTbl < ActiveRecord::Base
  has_many :events, :dependent => :destroy
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  validates_uniqueness_of :email, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user_tbl!
  
  def index
    @my_events = Event.where(:user_id => current_user_tbl.id).limit(6)
    @events = Event.limit(6)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end   
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  
  before_filter :authenticate_user_tbl!
  
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
  def create
    @event = Event.new(params[:event])
    @event.user_id = current_user_tbl.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
    
  end
  
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end
  
  def new
    @event = Event.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
      
    end
  end
  
  # GET /event/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # PUT /event/1
  # PUT /event/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /event/1
  # DELETE /event/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to @event }
      format.json { head :no_content }
    end
  end  
end

app/controllers/events_controller.rb
class EventController < ApplicationController
  
  before_filter :authenticate_user_tbl!
  
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
  def create
    @event = Event.new(params[:event])
    @event.user_id = current_user_tbl

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
    
  end
  
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end
  
  def new
    @event = Event.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
      
    end
  end
  
  # GET /event/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # PUT /event/1
  # PUT /event/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /event/1
  # DELETE /event/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to @event }
      format.json { head :no_content }
    end
  end  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(params[:micropost])

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render json: @micropost, status: :created, location: @micropost }
      else
        format.html { render action: "new" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/dashboard/index.html.erb
		
		<div id="headline">
			<div class="padding">
				<div class="selections">
					<ul>
						<li><a class="active" href="#">BBQ on the quad  <span>Tomorrow 8:00am</span></a></li>
						<li><a href="#">Matt's Poetry Slam  <span>Tomorrow 4:30pm</span></a></li>
						<li><a href="#">Hike on the ord  <span>Tuesday 4:30pm</span></a></li>
						<li><a href="#">KEGGER @ Petersburg  <span>Friday 10:30pm</span></a></li>
						<li><a href="#">friday night Magic  <span>Friday 10:30pm</span></a></li>
					</ul>
				</div>
				<div class="infoBox">
					<h3>BBQ on the quad</h3>
					<p><img src="../assets/sample/bbq.jpg" hspace="10" align="left">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean facilisis, purus eu fringilla lacinia, urna eros mattis quam, at posuere lorem felis eu purus. Integer augue nulla, varius et tempus in, consequat vel nisl. Quisque viverra quam et nisl accumsan aliquam. Donec venenatis rutrum cursus.
					<a href="#">View More</a></p>
				</div>
				<br class="clear" />
				<p class="small" style="margin-top:5px;"><a href="#">View all</a></p>
			</div>
		</div>
		<div>
			<div id="eventFeed">
				<div class="padding">
					<div class="header">
						<h4>Event Feed</h4>
					</div>
					<ul>
						<% 
						if @events.size > 0
							@events.each do |event| %>
							<li>
								<%= link_to event.name, event %>	
							</li>
							<% end
						else %>
							<p class="small" align="center">You do not have any events.</p>
						<% end %>
					</ul>
				</div>
			</div>
			<div id="myEvents">
				<div class="padding">
					<a href="../event/new" id="createEventButton">Create Event</a>
					<ul>
						<% 
						if @my_events.size > 0
							@my_events.each do |event| %>
							<li>
								<%= link_to event.name, event %>	
							</li>
							<% end
						else %>
							<p class="small" align="center">You do not have any events.</p>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
		<script type="text/javascript">
		$('#headline .selections a').bind('click', function() {
			$('#headline .selections a').removeClass('active');
			$(this).addClass('active');
			//do ajax stuff here for infoBox
			
			return false;
		});
		</script>

app/views/event/edit.html.erb
<div class="input">
        <%= form_tag(:event, :method => "put") %>
            <label for="name">Name of the Event:</label>
            <input name="event[name]" type="text" value="<%=@event.name %>" /><br />
            <label for="location">Location:</label>
            <input name="event[location]" type="text" value="<%=@event.location %>"/><br />
            <label for="desc">Description:</label>
            <textarea name="event[description]" rows="5" cols="15"><%=@event.description %></textarea><br />
            <label for="timeStart">When:</label>
            <input name="event[timeStart]" type="text" value="<%=@event.timeStart %>"/>
            <label for="timeEnd"></label>
            <input name="event[timeEnd]" type="text" value="<%=@event.timeEnd %>"/><br />
            <label for="type">Type of Event:</label>
            <input name="type" type="text"/><br />
            <label for="private">Privacy:</label>
            <select name="private">
            <option value="private">Private</option>
            <option value="public">Public</option>
            </select><br/>
            <label for="sharable">Flyers:</label>
            <input name="sharable"type="file" /><br>
            <label for="photo">Photo:</label>
            <input name="photo"type="file" /><br>
            
            <%= submit_tag("Edit Event") %>
            </form>
		</div>		

<%= button_to "Back", events_path, :method => :get %>


<style>
.input{
	margin:auto;
	width:500px;
	min-height:300px;
	background-color:#EEEEEE;
	
	padding-top:50px;
	-moz-border-radius:5px;
	-webkit-border-radius:5px;

}

label {
	display:block;
	font-weight:bold;
	float:left;
	width:160px;
	text-align:right;
	color:#66cc00;
}
</style>

app/views/event/index.html.erb
<h2>Listing events</h2>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>UserID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.id %></td>
    <td><%= event.name %></td>
    <td><%= event.user_id %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/event/new.html.erb
<%= form_for @event, :url => { :action => "create" }, :html => {:class => "input"} do |f| %>
  <%= label_tag(:name, "Event Name") %>
  <%= f.text_field :name %><br />
  <%= label_tag(:location, "Location") %>
  <%= f.text_field :location %><br />
  <%= label_tag(:description, "Description") %>
  <%= f.text_area :description, :size => "60x12" %><br />
  <%= f.submit "Create Event" %>
<% end %>

<!--<div class="input">
        <form accept-charset="UTF-8" action="/event" class="new_event" id="new_event" method="post">
            <label for="name">Name of the Event:</label>
            <input name="event[name]" type="text" /><br />
            <label for="location">Location:</label>
            <input name="event[location]" type="text"/><br />
            <label for="desc">Description:</label>
            <textarea name="event[description]" rows="5" cols="15"></textarea><br />
            <label for="timeStart">When:</label>
            <input name="timeStart" type="text"/>
            <label for="timeEnd"></label>
            <input name="event[timeEnd]" type="text"/><br />
            <label for="type">Type of Event:</label>
            <input name="type" type="text"/><br />
            <label for="private">Privacy:</label>
            <select name="private">
            <option value="private">Private</option>
            <option value="public">Public</option>
            </select><br/>
            <label for="sharable">Flyers:</label>
            <input name="sharable"type="file" /><br>
            <label for="photo">Photo:</label>
            <input name="photo"type="file" /><br>
            
            <input name="commit" type="submit" value="Submit" />
            </form>
		</div>		

<%= button_to "Back", events_path, :method => :get %>
-->

<style>
.input{
	margin:auto;
	width:300px;
	min-height:300px;
	background-color:#EEEEEE;
	padding:15px;
	padding-top:20px;
	-moz-border-radius:5px;
	-webkit-border-radius:5px;

}

label {
	margin-top:10px;
	display:block;
	font-weight:bold;
	width:160px;
	color:#66cc00;
}
input[type=text] {
	width:200px;	
}
textarea {
	width:200px;	
}
}
</style>

app/views/event/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>id</b>
  <%= @event.id %>
</p>

<p>
  <b>Event name:</b>
  <%= @event.name %>
</p>
<p>
  <b>Event Location:</b>
  <%= @event.location %>
</p>
<p>
  <b>Event Description</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back to Events', "/event" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OtterEvents</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body class="dashboard">
<div id="stripe">
	<div id="stripeInner">
		<div id="loginTools">
			<% if user_tbl_signed_in? -%>
			You are logged in as 
			<%= link_to current_user_tbl.email.split("@").first, "/dashboard", :class => "button" %>
			<%= link_to 'Sign out', destroy_user_tbl_session_path, :method => :delete, :class => "button" %>
			<% else %>
			<%= link_to 'Sign In', new_user_tbl_session_path, :class => "button" %>
			<%= link_to 'Register', new_user_tbl_registration_path, :class => "button" %>
			<% end %>
		</div>
	</div>
</div>
<div id="container">
	<div id="header">
		<% if notice -%>
		<p class="notice"><%= notice %></p>
		<%end
		 else if alert -%>
       	<p class="alert"><%= alert %></p>
       	<% end %>
		<div class="logo" align="left"><img src="../assets/otter_events_small.png" /></div>
		<div id="nav">
			
		</div>
	</div>
	<div id="content">
		<%= yield %>
	</div>
</div>
<div id="footer">
	<p>Copyright 2012 - Otter Events.</p>
	<p>Otter Events is in no way affiliated with California State University, Monterey Bay</p>
</div>



</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @micropost.user_id %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>Listing users</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>